apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-helm.fullname" . }}
  labels:
    {{- include "example-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "example-helm.selectorLabels" . | nindent 4 }}
