---
- name: Install Prometheus Node Exporter on Ubuntu VMs
  hosts: Ubuntus
  become: yes
  vars:
    node_exporter_version: "1.6.1"  # Default version, choose the desired version
    node_exporter_user: "node_exporter"
    node_exporter_port: 9100

  tasks:
    - name: Ensure node_exporter user exists
      ansible.builtin.user:
        name: "{{ node_exporter_user }}"
        state: present
        shell: /usr/sbin/nologin

    - name: Download Prometheus Node Exporter
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/usr/local/bin/"
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: "/usr/local/bin/node_exporter"

    - name: Create Node Exporter service
      ansible.builtin.template:
        src: "node_exporter.service.j2"
        dest: "/etc/systemd/system/node_exporter.service"
      notify: restart node_exporter

    - name: Reload systemd and enable Node Exporter
      ansible.builtin.systemd:
        daemon_reload: yes
        name: node_exporter
        enabled: yes
        state: started

  handlers:
    - name: restart node_exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: restarted
